name = "anytomarkdown"
main = "src/index.ts"
compatibility_date = "2023-06-28"

account_id = "your_account_id_here" # 替换为您的Cloudflare账户ID

[build]
command = "npm run build"

[ai]
binding = "AI" # 绑定到Cloudflare Workers AI服务

[vars]
ENVIRONMENT = "production"