name = "anytomarkdown"
main = "src/index.ts"
compatibility_date = "2023-10-30"
usage_model = "bundled"

# 添加你的账户ID
account_id = "f44f3de1a0ae3985f9bc7bdb469128bf"

# AI绑定
[ai]
binding = "AI"

# 环境变量
[vars]
# 允许的CORS来源，用逗号分隔
ALLOWED_ORIGINS = "*"

# 生产环境配置
[env.production]
# 可以添加生产环境特定配置

# 开发环境配置
[env.development]
# 开发环境特定配置 